import java.util.*;
public class exception {
    private static final Scanner scanner = new Scanner(System.in);
    public static void main(String[] args) {
        int[] array = {1, 2, 3};

        // int input = scanner.nextInt();
        // if(input >= array.length) throw new IndexOutOfBoundsException("ERROR: Anda mengakses lebih dari panjang array");
        // else System.out.println(array[input]);
        // try {
        //     int input = scanner.nextInt();
        //     if(input < 0) throw new IllegalArgumentException("ERROR: Value tidak bisa dibawah 0");
        //     System.out.println(array[input]);
        //     System.out.println(array[0]/0);
        // } catch(IllegalArgumentException e){
        //     System.out.println(e.getMessage());
        // } catch(InputMismatchException e){
        //     System.out.println("ERROR: Input tidak sesuai");
        // } catch (IndexOutOfBoundsException e) {
        //     System.out.println("ERROR: Anda mengakses lebih dari panjang array");
        //     // System.out.println(e.getMessage());
        //     // System.out.println(e.toString());
        //     // e.printStackTrace();
        // } catch(Exception e) {
        //     System.out.println("Terjadi eksepsi yang tidak diketahui.");
        // }
    }
}
/*
 * Exception ArrayIndexOutOfBound di class angkot bus
 * Penggunaan class Exception general
 * Penggunaan class throw (apabila terjadi ERROR dikembalikan ke main program)
 */
